# 当前 compose 仅用于开发环境
version: '1'

volumes:
  mongodb_data:
  mysql_data:


services:
  mongo:
    image: bitnami/mongodb:5.0.8
    volumes:
      - 'mongodb_data:/Users/Shared/mongodb'
    ports:
      - "27017:27017"

  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - 'mysql_data:/Users/Shared/mysql'
    ports:
      - "3306:3306"
