TEST_VALUE:
  name: express-cookie

NODE_ENV:
  name: "development"
MONGODB_CONFIG:
  name: "ignition_test" # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: "mongodb://localhost:27017" # 数据库链接地址
  username: "root" # 数据库链接用户名
  password: "root123" # 数据库链接密码
  database: "ignition_test" # 数据库名
  entities: "mongo" # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能

REDIS_CONFIG:
  host: "localhost" # redis 链接
  port: 6379 # redis 端口
  auth: "" # redis 连接密码，没有显式设置都是空
  db: 1 # redis 数据库，0开始

# 飞书 配置
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID:
  FEISHU_APP_SECRET:
  APP_TOKEN_CACHE_KEY:

# 本地 配置
LOCAL_USER_CONFIG:
  SECRET: ignition-test

# Github 配置
GITGUB_CONFIG:
  CLIENT_ID:
  CLIENT_SECRET:

# Google 配置
GOOGLE_CONFIG:
  CLIENT_ID:
  CLIENT_SECRETS:
